In [89]:
!pip install numpy pandas openpyxl

  Obtaining dependency information for openpyxl from https://files.pythonhosted.org/packages/c0/da/977ded879c29cbd04de313843e76868e6e13408a94ed6b987245dc7c8506/openpyxl-3.1.5-py2.py3-none-any.whl.metadata
  Obtaining dependency information for et-xmlfile from https://files.pythonhosted.org/packages/96/c2/3dd434b0108730014f1b96fd286040dc3bcb70066346f7e01ec2ac95865f/et_xmlfile-1.1.0-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.9 kB 220.2 kB/s eta 0:00:01
   ----------- --------------------------- 71.7/250.9 kB 393.8 kB/s eta 0:00:01
   ----------- --------------------------- 71.7/250.9 kB 393.8 kB/s eta 0:00:01
   -------------- ------------------------ 92.2/250.9 kB 327.7 k


[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
# 1.1 Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5
import numpy as np 

my_array = np.arange(5, 101, 5)
print(my_array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [9]:
# 2.1 Из полученного массива получить массив с кратными 10 числами
array10 = np.extract(my_array % 10 == 0, my_array)
print(array10)

[ 10  20  30  40  50  60  70  80  90 100]


In [11]:
# 3.1 Получить двумерный массив с двумя столбцами
array2d = array10.reshape(5, 2)
print(array2d)

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [13]:
# 4.1 Получить двумерный массив с двумя столбцами
my_array2 = array2d - 5
print(my_array2)

[[ 5 15]
 [25 35]
 [45 55]
 [65 75]
 [85 95]]


In [16]:
# 5.1 Соедините массивы, полученные в п.3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы.
stacked_arrays = np.hstack([array2d, my_array2])
print(stacked_arrays)

[[ 10  20   5  15]
 [ 30  40  25  35]
 [ 50  60  45  55]
 [ 70  80  65  75]
 [ 90 100  85  95]]


In [20]:
# 6.1 Разделите 2 и 3 строку на 4 верхних строки my_array. Используйте .T для транспонирования матрицы
div_res = stacked_arrays[1] / stacked_arrays [3] 
div_res2 = stacked_arrays[2] / stacked_arrays [3]

print(div_res)
print(div_res2)

[0.42857143 0.5        0.38461538 0.46666667]
[0.71428571 0.75       0.69230769 0.73333333]


In [25]:
# 7.1. Оставить только те значения, которые не изменились после деления
stacked_arrays2 = stacked_arrays.copy().astype(float)
stacked_arrays2[1] = div_res
stacked_arrays2[2] = div_res2

print(f'{stacked_arrays} \n')

equal_rows = np.all(stacked_arrays == stacked_arrays2, axis=1)
unchanged = stacked_arrays2[equal_rows]

print(unchanged)

[[ 10  20   5  15]
 [ 30  40  25  35]
 [ 50  60  45  55]
 [ 70  80  65  75]
 [ 90 100  85  95]] 

[[ 10.  20.   5.  15.]
 [ 70.  80.  65.  75.]
 [ 90. 100.  85.  95.]]


In [26]:
# 8.1. Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки
unchanged[[0, 2]] = unchanged[[2, 0]]
print(unchanged)

[[ 90. 100.  85.  95.]
 [ 70.  80.  65.  75.]
 [ 10.  20.   5.  15.]]


In [27]:
# 9.1. Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды np.mean(), np.median(), np.std().
mean_values = np.mean(unchanged, axis=1)
median_values = np.median(unchanged, axis=1)
std_values = np.std(unchanged, axis=1)

print('Mean: ', mean_values)
print('Median: ', median_values)
print('Std: ', std_values)


Mean:  [92.5 72.5 12.5]
Median:  [92.5 72.5 12.5]
Std:  [5.59016994 5.59016994 5.59016994]


In [31]:
# 10.1.	Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на max() вдоль строк.
maximum = np.max(unchanged, axis=1, keepdims=True)

norm_res = unchanged / maximum
print(f'{maximum} \n')
print(norm_res)

[[100.]
 [ 80.]
 [ 20.]] 

[[0.9    1.     0.85   0.95  ]
 [0.875  1.     0.8125 0.9375]
 [0.5    1.     0.25   0.75  ]]


In [1]:
# 2.1 Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.
import pandas as pd
df = pd.read_csv("Lab2_Files/Global Population Trends(2016-2022).csv")
df

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55              63      37.342       7.027   
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38              61      32.516       8.266   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[1073 rows x 12 columns]

In [4]:
# 2.2 Считайте несколько первых записей таблицы (head())

df.head(10)

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   
5      Albania  2017                -                -                -   
6      Albania  2018        2,866,376        1,728,969        1,137,407   
7      Albania  2019        2,854,191        1,747,593        1,106,598   
8      Albania  2020        2,837,849        1,762,645        1,075,204   
9      Albania  2021        2,811,666        1,770,478        1,041,188   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   
5                105              79      10.870       8.150          1.491   
6                105              79      10.517       8.308           1.44   
7                104              79      10.343       8.480          1.414   
8                104              77      10.285      10.785            1.4   
9                  -              76      10.240      11.325           1.39   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8           3  
2                  46.3           3  
3                  44.8           3  
4                  43.4           3  
5                   8.3           -  
6                   8.3           0  
7                   8.4           0  
8                   8.4          -1  
9                   8.4          -1

In [5]:
# 2.3 Определите размерность данного фрейма (shape())

df.shape

(1073, 12)

In [6]:
# 2.4 Выведите название заголовков столбцов фрейма (columns)

df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [7]:
# 2.5 Получите описание всех переменных (полей) (info())

df.info

<bound method DataFrame.info of           Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Ex

In [8]:
# 2.6 Удалите строки, не содержащие значения в столбце «Total Population» - “-” 

df1=df[df['Total Population']!='-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

In [9]:
# 2.7 Получите описательную статистику по переменным (например, max(), min(), describe())

print(df1.describe())
print(df1.max())
print(df1.min())
print(df1['Total Population'].describe())

              Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000
Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                  85
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                       5
dtype: object
Country                  Afghanistan
Year                            2018
Total Population           1,057,198
Urban Population                   -
Rural Population   

In [10]:
# 2.8 Выполните сортировку данных по нескольким критериям

df2 = df1.sort_values(by=["Birth Rate", "Total Population", "Life Expectancy"])
print(df2)

            Country  Year Total Population Urban Population Rural Population  \
629          Monaco  2021           36,686           36,686                -   
628          Monaco  2020           36,922           36,922                -   
627          Monaco  2019           37,034           37,034                -   
18   American Samoa  2021           45,035           39,257            5,778   
16   American Samoa  2019           47,321           41,239            6,082   
..              ...   ...              ...              ...              ...   
864         Somalia  2018       15,411,094        6,930,523        8,480,571   
694           Niger  2021       25,252,722        4,230,083       21,022,639   
693           Niger  2020       24,333,639        4,045,711       20,287,928   
692           Niger  2019       23,443,393        3,872,145       19,571,248   
691           Niger  2018       22,577,058        3,708,282       18,868,776   

    Population Density Life Expectancy 

In [12]:
# Форматирование "Общей численности населения" для поиска

df1Fl = df1.copy()
df1Fl["Total Population"] = df1Fl["Total Population"].str.replace(',', '').astype(float)
df1Fl

Country  Year  Total Population Urban Population Rural Population  \
1     Afghanistan  2018        36686784.0        9,353,296       27,333,488   
2     Afghanistan  2019        37769499.0        9,727,157       28,042,342   
3     Afghanistan  2020        38972230.0       10,142,913       28,829,317   
4     Afghanistan  2021        40099462.0       10,551,772       29,547,690   
6         Albania  2018         2866376.0        1,728,969        1,137,407   
...           ...   ...               ...              ...              ...   
1067       Zambia  2021        19473125.0        8,800,295       10,672,830   
1069     Zimbabwe  2018        15052184.0        4,848,158       10,204,026   
1070     Zimbabwe  2019        15354608.0        4,945,719       10,408,889   
1071     Zimbabwe  2020        15669666.0        5,052,214       10,617,452   
1072     Zimbabwe  2021        15993524.0        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56              63      36.927       6.981   
2                    58              64      36.466       6.791   
3                    60              63      36.051       7.113   
4                     -              62      35.842       7.344   
6                   105              79      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -              61      34.511       6.973   
1069                 39              61      32.074       7.972   
1070                 40              61      31.518       8.043   
1071                 41              61      31.009       8.132   
1072                  -              59      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8           3  
2              4.87                  46.3           3  
3              4.75                  44.8           3  
4             4.643                  43.4           3  
6              1.44                   8.3           0  
...             ...                   ...         ...  
1067          4.308                  40.2           3  
1069          3.659                    38           2  
1070          3.599                  37.1           2  
1071          3.545                  36.6           2  
1072          3.491                  35.7           2  

[864 rows x 12 columns]

In [13]:
# 2.9 Выведите название страны, которая имеет максимальную численность населения
sorted_population = df1Fl.sort_values(by=["Total Population"])
print("Страна с максимальной численностью населения =", sorted_population["Country"].iloc[-1])


Страна с максимальной численностью населения = China


In [14]:
# 2.10 	Выведите название страны, которая имеет минимальную численность населения
print("Страна, с минимальной численностью населения =", sorted_population["Country"].iloc[0])

Страна, с минимальной численностью населения = Tuvalu


In [15]:
# 2.11 Экспорт фрейма в MS Excel

df1Fl.to_excel("Lab2_Files/Lab2.xlsx", sheet_name="Lab2")